server <- function(input,output,session){
  output$wikiUI<-renderUI({
    tagList(
      h2("How to Play?"),
      p("Computer will generate a 4 digit number randomly with each of the 4 digits being unique i.e. number cant be 1899 since 9 is repeated here. (Note: digits range from 0 to 9 and 0 can come in first place as well say 0123 as an example).",style = "font-family: 'times'; font-si16pt"),
      p("You have to input 4 digit number accordingly with the goal to guess the number generated by the computer.",style = "font-family: 'times'; font-si16pt"),
p("For each number you input u will get number of bulls and cows. Let's say the actual number is 3719 and the number you input is 1629. For this number computer will responds with ",style = "font-family: 'times'; font-si16pt",strong("1 B 2 C"), em("(1 Bull and 2 Cows) 1 Bull implies 1 digit among the 4 you guess is correct and in correct position and 2 cows implies 2 digits are correct but are not in the correct position")),
      p("Your Goal is to get 4 B 0 C.",style = "font-family: 'times'; font-si16pt"),
      br()
    )
  })


  inputlist<-reactiveValues(guess=character(0),
                            guesscheck=NA,
                            ntrials=character(0),quit=FALSE,
                            num=as.character(sample(0:9,4,replace = F))
                            )

  #restart button
  observeEvent(input$restart,{
    inputlist$guess<-character(0)
    inputlist$guesscheck<-NA
    inputlist$num<-as.character(sample(0:9,4,replace = F))
    inputlist$ntrials=character(0);inputlist$quit=F
    inputlist$scoreframe=data.frame(Guess=" ",...=" ",Bull.Cow=" ")
  })

  #submit button
  observeEvent(input$submit,{
    guessnumC=strsplit(as.character(input$guessnum),"")[[1]]
    if(length(guessnumC)==3){guessnumC=c("0",guessnumC)}
    if(length(guessnumC)<3){guessnumC=NA}
    if(length(guessnumC)>4){guessnumC=guessnumC[1:4]}
    if(any(is.na(guessnumC))){pasteguessnumC=NA}else{
      pasteguessnumC=paste0(guessnumC,collapse = "")}
    inputlist$guess=c(inputlist$guess[!is.na(inputlist$guess)],pasteguessnumC)
    inputlist$guesscheck=c(inputlist$guesscheck[!is.na(inputlist$guesscheck)],
                           CowBullFunc(inputlist$num,guessnumC))
    inputlist$ntrials=length(inputlist$guess)
    inputlist$scoreframe=data.frame(Guess=inputlist$guess,
                          ...=" ",
                          Bull.Cow=inputlist$guesscheck)

  })

  #GiveUp
  observeEvent(input$quit,{inputlist$quit=T})

  output$scorecard<-renderTable({inputlist$scoreframe})
  output$winmessage<-renderPrint({
    if(!any(is.na(inputlist$guesscheck))){
    if(inputlist$guesscheck[length(inputlist$guesscheck)]=="4 B 0 C"){
      cat("You Win!! \n
                        No. of Trials = ",inputlist$ntrials,"\n")
    }}
      if(inputlist$quit){
        actnum=paste0(inputlist$num,collpase="")
        cat("You Didn't Complete the game \n",
            "You Quitted after trying ",inputlist$ntrials," times\n   The number was ",
            actnum)
    }
  })


 }
